//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crudNarAsp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NaturEntities : DbContext
    {
        public NaturEntities()
            : base("name=NaturEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<FacturaDetalle> FacturaDetalle { get; set; }
        public DbSet<Facturas> Facturas { get; set; }
        public DbSet<GestionClientes> GestionClientes { get; set; }
        public DbSet<GestionProductos> GestionProductos { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Vendedores> Vendedores { get; set; }
    }
}
